'use strict';

const fs = require('node:fs');
const path = require('node:path');

function readConfig(configPath) {
  try {
    const input = JSON.parse(fs.readFileSync(configPath, 'utf8'));
    if (input.schema !== 1 || input.configured !== true || !/^[A-Za-z0-9][A-Za-z0-9-]{0,38}$/.test(input.owner) || !/^[A-Za-z0-9_.-]+$/.test(input.repo) || ['.', '..'].includes(input.repo)) return null;
    return { owner: input.owner, repo: input.repo, awaitingFirstRelease: input.awaitingFirstRelease === true, releaseUrl: `https://github.com/${input.owner}/${input.repo}/releases/latest` };
  } catch { return null; }
}

function createUpdater({ app, send = () => {}, isBusy = () => false, beforeInstall = async () => {}, configPath = path.join(process.resourcesPath || '', 'update-config.json'), platform = process.platform, environment = process.env, updaterFactory = () => require('electron-updater').autoUpdater }) {
  const config = readConfig(configPath);
  const portable = Boolean(environment.PORTABLE_EXECUTABLE_FILE || environment.PORTABLE_EXECUTABLE_DIR);
  let updater, started = false, disposed = false, checking = null, installing = false;
  let firstTimer, intervalTimer;
  const listeners = [];
  const state = {
    status: !config ? 'unconfigured' : !app.isPackaged ? 'development' : platform !== 'win32' || portable ? 'manual' : 'idle',
    currentVersion: app.getVersion(),
    availableVersion: null,
    progress: 0,
    configured: Boolean(config),
    automatic: Boolean(config && app.isPackaged && platform === 'win32' && !portable),
    releaseUrl: config?.releaseUrl || null,
    message: !config ? 'GitHub 배포 저장소가 연결되지 않았습니다.' : !app.isPackaged ? '개발 실행에서는 자동 업데이트를 설치하지 않습니다.' : portable ? '설치 없이 실행하는 버전입니다. 새 버전은 다운로드 페이지에서 받아 주세요.' : platform !== 'win32' ? 'Windows 설치 버전에서 자동 업데이트를 사용할 수 있습니다.' : config.awaitingFirstRelease ? '배포 경로가 준비되었습니다. GitHub에 첫 릴리스가 공개되면 새 버전을 자동으로 확인합니다.' : '새 버전을 자동으로 확인합니다.',
  };
  const getState = () => ({ ...state });
  const emit = (patch) => {
    if (disposed) return getState();
    Object.assign(state, patch);
    try { send(getState()); } catch { /* A closed renderer must not affect the updater. */ }
    return getState();
  };
  function bind(event, handler) { updater.on(event, handler); listeners.push([event, handler]); }
  function ensureUpdater() {
    if (updater || !state.automatic || disposed) return updater;
    updater = updaterFactory();
    updater.autoDownload = true;
    updater.autoInstallOnAppQuit = false;
    updater.allowPrerelease = false;
    updater.allowDowngrade = false;
    updater.disableWebInstaller = true;
    // app-update.yml is generated by electron-builder; never accept a feed from the renderer.
    bind('checking-for-update', () => emit({ status: 'checking', message: '새 버전을 확인하고 있습니다.' }));
    bind('update-available', info => emit({ status: 'downloading', availableVersion: String(info.version), progress: 0, message: '새 버전을 내려받고 있습니다. 자리 배치는 계속 사용할 수 있습니다.' }));
    bind('update-not-available', () => emit({ status: 'idle', availableVersion: null, progress: 0, message: '최신 버전입니다.' }));
    bind('download-progress', progress => emit({ status: 'downloading', progress: Math.min(100, Math.max(0, Number(progress.percent) || 0)), message: '새 버전을 내려받고 있습니다.' }));
    bind('update-downloaded', info => emit({ status: 'downloaded', availableVersion: String(info.version), progress: 100, message: '새 버전이 준비되었습니다. 수업이 끝난 뒤 업데이트 적용을 눌러 주세요.' }));
    bind('update-cancelled', () => emit({ status: 'idle', progress: 0, message: '다운로드를 마치지 못했습니다. 나중에 다시 확인해 주세요.' }));
    bind('error', () => emit({ status: 'error', message: '업데이트에 연결하지 못했습니다. 인터넷과 GitHub 배포 상태를 확인해 주세요. 현재 버전은 계속 사용할 수 있습니다.' }));
    return updater;
  }
  async function check() {
    if (disposed || !state.automatic) return getState();
    if (isBusy()) return emit({ message: '발표가 끝난 뒤 업데이트를 확인합니다.' });
    if (checking || ['downloading', 'downloaded', 'installing'].includes(state.status)) return checking || getState();
    try {
      const service = ensureUpdater();
      checking = Promise.resolve(service.checkForUpdates()).then(result => {
        // electron-updater reports downloads through events and a separate promise.
        // Observe that promise too, so an interrupted download cannot become an unhandled rejection.
        result?.downloadPromise?.catch(() => emit({ status: 'error', message: '업데이트를 내려받지 못했습니다. 현재 버전은 계속 사용할 수 있습니다.' }));
        return getState();
      }).catch(() => emit({ status: 'error', message: '업데이트 확인에 실패했습니다. 현재 버전은 계속 사용할 수 있습니다.' })).finally(() => { checking = null; });
      return await checking;
    } catch {
      checking = null;
      return emit({ status: 'error', message: '업데이트를 시작하지 못했습니다. 나중에 다시 확인해 주세요.' });
    }
  }
  async function install() {
    if (disposed || !state.automatic || state.status !== 'downloaded' || installing) return getState();
    if (isBusy()) return emit({ message: '발표 중에는 업데이트를 설치하지 않습니다. 발표가 끝난 뒤 눌러 주세요.' });
    installing = true;
    try {
      await beforeInstall();
      // Recheck after async saving: a presentation may have started in the meantime.
      if (disposed || isBusy()) return emit({ message: '자리 배치를 저장했습니다. 발표가 끝난 뒤 업데이트를 적용해 주세요.' });
      emit({ status: 'installing', message: '자료를 저장했습니다. 업데이트를 설치한 뒤 자리온을 다시 실행합니다.' });
      updater.quitAndInstall(false, true);
    } catch {
      emit({ status: 'downloaded', message: '자료 저장 또는 설치 준비를 완료하지 못했습니다. 업데이트 적용을 다시 눌러 주세요.' });
    } finally { installing = false; }
    return getState();
  }
  function start() {
    if (started || disposed) return getState();
    started = true;
    if (state.automatic) {
      firstTimer = setTimeout(() => { void check(); }, 15000);
      intervalTimer = setInterval(() => { void check(); }, 6 * 60 * 60 * 1000);
      firstTimer.unref?.(); intervalTimer.unref?.();
    }
    return getState();
  }
  function dispose() {
    disposed = true;
    clearTimeout(firstTimer); clearInterval(intervalTimer);
    for (const [event, handler] of listeners) updater?.removeListener(event, handler);
  }
  return { getState, check, install, start, dispose };
}

module.exports = { createUpdater, readConfig };
